package config;

public enum Property {
    DROP_AND_RECREATE_TABLES,
    EXECUTE_BATCH_AFTER,
    EXTRACT_KEY_WORDS,
    NUMBER_OF_KEY_WORDS,
    SIMILARITY_BATCH,
    FIND_SIMILARITIES,
    FIND_SIMILARITIES_IN_BATCHES,
    TOP_K,
    BIG_CSV_PATH,
    TEST_CSV_PATH,
    NORMAL_CSV_PATH,
    DB_URL
}
