package config;

public enum Property {
    DROP_AND_RECREATE_TABLES,
    EXECUTE_BATCH_AFTER,
    SEARCH,
    SEARCH_TOP_K,
    EXTRACT_KEY_WORDS,
    EXTRACT_MEMBER_KEY_WORDS,
    EXTRACT_POLITICAL_PARTY_KEY_WORDS,
    EXTRACT_SPEECH_KEY_WORDS,
    NUMBER_OF_KEY_WORDS,
    FIND_SIMILARITIES,
    FIND_SIMILARITIES_IN_BATCHES,
    SIMILARITY_BATCH,
    TOP_K_SIMILARITIES,
    BIG_CSV_PATH,
    TEST_CSV_PATH,
    NORMAL_CSV_PATH,
    DB_URL
}
